pipeline {
    agent {
        label 'devpod'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup Python') {
            steps {
                dir('jenkins-pipeline') {
                    sh '''
                        set -e

                        echo "Project directory:"
                        pwd

                        echo "Mise configuration:"
                        ls -la mise.toml

                        mise install

                        echo "Python:"
                        mise exec python -- python --version
                    '''
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('jenkins-pipeline') {
                    sh '''
                        set -e

                        mise exec python -- python -m pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                dir('jenkins-pipeline') {
                    sh '''
                        set -e

                        mise exec python -- python -m pytest
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Python CI build successful!'
        }

        failure {
            echo 'Python CI build failed!'
        }
    }
}
