pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage ('Setup Python') {
            steps {
                dir('multi-branchpipelineautomation') {
                    sh '''
                        set -e 

                        echo "Project directory"
                        pwd

                        echo "Mise Configuration:"
                        ls -la mise.toml

                        mise Install

                        echo "Python:"
                        mise exec python -- python --version
                       '''
                }
            }    
        }
        
        stage('Test') {
            steps {
                
                dir('multi-branchpipelineautomation') {
                    sh '''

                       'pytest -v'
                }
            }
        }
    } 

    post {
        success {
            echo "python CI build Successful!"
        }

        failure {
            echo "python CI build Failed!"
        }


    }
}
