pipeline {
    agent {
        label 'jenkins-agent'
    }

    stages {

        stage('Test') {
            steps {
                sh './scripts/test.sh'
            }
        }

        stage('Security Scan') {
            steps {
                sh './scripts/security-scan.sh'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t security-scanning-cicd:${BUILD_NUMBER} .'
            }
        }

        stage('Trivy Scan') {
            steps {
                sh '''
                    trivy image \
                      --severity HIGH,CRITICAL \
                      --exit-code 1 \
                      security-scanning-cicd:${BUILD_NUMBER}
                '''
            }
        }
    }

    post {
        success {
            echo 'Security pipeline completed successfully.'
        }

        failure {
            echo 'Security pipeline failed.'
        }

        always {
            echo 'Pipeline execution finished.'
        }
    }
}
