pipeline {
    agent {
        label 'jenkins-agent'
    }

    stages {

        stage('Test') {
            steps {
                dir('security-scanning-cicd') {
                    sh './scripts/test.sh'
                }
            }
        }

        stage('Source Security Scan') {
            steps {
                dir('security-scanning-cicd') {
                    sh './scripts/security-scan.sh'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('security-scanning-cicd') {
                    sh 'docker build -t security-scanning-cicd:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Trivy Container Scan') {
            steps {
                dir('security-scanning-cicd') {
                    sh '''
                        trivy image \
                          --severity HIGH,CRITICAL \
                          --exit-code 1 \
                          security-scanning-cicd:${BUILD_NUMBER}
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Security pipeline completed successfully.'
        }

        failure {
            echo 'Security pipeline failed.'
        }

        always {
            echo 'Pipeline execution finished.'
        }
    }
}
